//http requests methods

//these are methods which helps us to perform and process http request
//generated by user/client side
//there are five types of http methods avaiable for several purpose

//1. GET    -> it is the first or we can say default method which will run whenever
        //any user visits a webpage or to route.

        //so basically if we want to get some data or response from server then
        //we can use GET method


//2. POST   -> it is used to post or add any new data or information to server from
            //client side


//3. PUT    -> it is used to update or replace  any existing data resource with
                //a completely new one.
                //e.g...if there is a signup form and user wants to update or replace
                //all fields of form then in such case we can use PUT method


//4. PATCH  ->  if you send a PATCH request to update a resource,
            // the server will only update the specified fields in the existing resource.

//5. DELETE -> it is used to delete any data resource from server
